services:
  db:
    restart: unless-stopped
    image: postgres
    volumes:
      - dev_db_data:/var/lib/postgresql/data
      - ./dev-database/backup/:/tmp/backup
      - ./dev-database/init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file: .env.dev
    ports:
      - 5433:5432

volumes:
  dev_db_data: